import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 150,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza',],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 120,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood',],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 50,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Burger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 25,
    cookTime: '5-10',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 40,
    cookTime: '10-15',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 90,
    cookTime: '15-20',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza',],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 80,
    cookTime: '10-20',
    favorite: false,
    origins: ['Indian'],
    stars: 4.3,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger',],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 100,
    cookTime: '15-20',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza',],
  },
  {
    id:'9',
    name: 'Butter Paneer',
    price: 200,
    cookTime: '20-25',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/paneer.jpg',
    tags: ['Lunch'],
  },
  {
    id:'10',
    name: 'Dosa',
    price: 70,
    cookTime: '20-25',
    favorite: true,
    origins: [ 'South indian','india',],
    stars: 4.0,
    imageUrl: 'assets/dosa.jpg',
    tags: ['Breakfast','Lunch',],
  },
  {
    id:'11',
    name: 'Gujrati Chali',
    price: 250,
    cookTime: '20-30',
    favorite: false,
    origins: ['Gujrat', 'india'],
    stars: 3.5,
    imageUrl: 'assets/gujrati.jpeg',
    tags: ['Lunch',],
  },
  {
    id:'12',
    name: 'Idli Sambar',
    price: 60,
    cookTime: '10-15',
    favorite: true,
    origins: [ 'South indian','india',],
    stars: 4.7,
    imageUrl: 'assets/idli.jpg',
    tags: ['Breakfast','Lunch',],
  },
  {
    id:'13',
    name: 'Chhola Bhatura',
    price: 75,
    cookTime: '10-20',
    favorite: false,
    origins: ['middle east','india'],
    stars: 4.0,
    imageUrl: 'assets/chhola.jpg',
    tags: ['Breakfast','Lunch'],
  },
  {
    id:'14',
    name: 'Masala Dosa',
    price: 80,
    cookTime: '20-25',
    favorite: true,
    origins: [ 'South indian','india',],
    stars: 4.7,
    imageUrl: 'assets/masala.jpg',
    tags: ['Breakfast','Lunch',],
  },
  
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 14 },
  { name: 'FastFood', count: 6 },
  { name: 'Pizza', count: 3 },
  { name: 'Breakfast', count: 4 },
  { name: 'Lunch', count: 6 },
  { name: 'SlowFood', count: 2 },
  { name: 'Burger', count: 2 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]
